wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683290036.792149
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.1
      8:
      - 5
