wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.14.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683292156.570519
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.11.3
      5: 0.14.2
      8:
      - 5
